export default [
"dancing a ballet ",
"washing an elephant ",
"rock climbing",
"shopping at the mall ",
"playing soccer ",
"flying a kite",
"going bowling ",
"scuba diving ",
"chasing a tornado",
"building a campfire ",
"sewing a dress ",
"filming a movie ",
"riding a carousel ",
"playing chess",
"finger painting ",
"visiting the zoo ",
"sewing on a button",
"ironing a shirt ",
"baking bread ",
"making a pizza",
"having a food fight ",
"paddling in a canoe ",
"delivering mail",
"riding a motorcycle ",
"flipping pancakes ",
"sorting laundry",
"playing hopscotch ",
"hailing a taxi ",
"landing an airplane",
"watering a garden ",
"mowing a lawn ",
"raking leaves",
"feeding the ducks ",
"building a sandcastle ",
"playing baseball",
"milking a cow ",
"setting up a tent ",
"whale watching",
"decorating for a party ",
"trick-or-treating ",
"walking with crutches",
"riding in a chairlift ",
"sumo wrestling ",
"digging a hole",
"riding bumper cars ",
"practicing ",
"karate hang-gliding",
"cutting someone's hair",
"swimming with dolphins",
"playing with playdough",
"going through airport security",
"filling up a car with gas",
"ordering food at a restaurant",
"operating a jackhammer",
"picking apples from a tree",
"gathering eggs from a hen house",
"watching a movie at the theater",
"climbing Mount Everest",
"going on an African safari",
"performing at a rock concert",
"playing at a piano recital",
"asking for an autograph",
"walking through a haunted house",
"opening birthday presents",
"body surfing at the beach",
"painting the walls in a room",
"being a flight attendant",
"washing windows on a building",
]