export default [

  "M-ping pong",
  "M-snowball",
  "M-roof",
  "M-fly",
  "M-fang ",
  "M-bicycle",
  "M-bear ",
  "M-cape ",
  "M-puppet",
  "M-piano ",
  "M-lipstick ",
  "M-salute",
  "M-hula hoop ",
  "M-penguin ",
  "M-banana peel",
  "M-whisper ",
  "M-popsicle ",
  "M-Frankenstein",
  "M-earthquake ",
  "M-yo-yo ",
  "M-road",
  "M-rain ",
  "M-alarm clock ",
  "M-dog leash",
  "M-chop ",
  "M-pajamas ",
  "M-slam dunk",
  "M-fiddle ",
  "M-seashell ",
  "M-jog",
  "M-seesaw ",
  "M-nap ",
  "M-cheerleader",
  "M-blind ",
  "M-beg ",
  "M-shopping ",
  "M-cart",
  "M-Michael Jackson ",
  "M-limbo ",
  "M-newspaper",
  "M-twist ",
  "M-rhinoceros ",
  "M-cow",
  "M-tickle ",
  "M-fetch ",
  "M-violin",
  "M-cage ",
  "M-cello ",
  "M-braid",
  "M-skateboard ",
  "M-stairs ",
  "M-trumpet",
  "M-mop ",
  "M-shovel ",
  "M-money",
  "M-soap ",
  "M-saddle ",
  "M-wink",
  "M-tree ",
  "M-Spider Man ",
  "M-think",
]