export default [
  "Will Smith",
  "defect",
  "standing ovation",
  "flag",
  "retaliate",
  "mascot",
  "shipwreck",
  "jet lag",
  "comfort zone",
  "alphabetize",
  "application",
  "college",
  "lifestyle",
  "level",
  "invitation",
  "applesauce",
  "crumb",
  "loyalty",
  "corduroy",
  "fizz",
  "shrink ray",
  "game plan",
  "personal bubble",
  "déjà vu",
  "Olympian ",
  "oil ",
  "procrastinate",
  "criticize ",
  "space-time continuum ",
  "ergonomic",
  "regret ",
  "teenager ",
  "organize",
  "baby monitor ",
  "Beethoven ",
  "streamline",
  "satellite ",
  "gratitude ",
  "journal",
  "a cappella ",
  "beanstalk ",
  "explore",
  "mine shaft ",
  "dismantle ",
  "weed killer",
  "tachometer ",
  "unemployed ",
  "portfolio",
  "pomp ",
  "evolution ",
  "apathy",
  "advertise ",
  "roundabout ",
  "sandbox",
  "conversation ",
  "negotiate ",
  "Zamboni",
  "silhouette ",
  "aisle ",
  "pendulum",
]
