export default [
  "VH-Will Smith",
  "VH-defect",
  "VH-standing ovation",
  "VH-flag",
  "VH-retaliate",
  "VH-mascot",
  "VH-shipwreck",
  "VH-jet lag",
  "VH-comfort zone",
  "VH-alphabetize",
  "VH-application",
  "VH-college",
  "VH-lifestyle",
  "VH-level",
  "VH-invitation",
  "VH-applesauce",
  "VH-crumb",
  "VH-loyalty",
  "VH-corduroy",
  "VH-fizz",
  "VH-shrink ray",
  "VH-game plan",
  "VH-personal bubble",
  "VH-déjà vu",
  "VH-Olympian ",
  "VH-oil ",
  "VH-procrastinate",
  "VH-criticize ",
  "VH-space-time continuum ",
  "VH-ergonomic",
  "VH-regret ",
  "VH-teenager ",
  "VH-organize",
  "VH-baby monitor ",
  "VH-Beethoven ",
  "VH-streamline",
  "VH-satellite ",
  "VH-gratitude ",
  "VH-journal",
  "VH-a cappella ",
  "VH-beanstalk ",
  "VH-explore",
  "VH-mine shaft ",
  "VH-dismantle ",
  "VH-weed killer",
  "VH-tachometer ",
  "VH-unemployed ",
  "VH-portfolio",
  "VH-pomp ",
  "VH-evolution ",
  "VH-apathy",
  "VH-advertise ",
  "VH-roundabout ",
  "VH-sandbox",
  "VH-conversation ",
  "VH-negotiate ",
  "VH-Zamboni",
  "VH-silhouette ",
  "VH-aisle ",
  "VH-pendulum",
]
