export default {
  "category":"Easy",
  "word":"cone",
  "wordDictionary":{
    "Easy":[
      "dance",
      "skip",
      "jumping",
      "jack"
    ],
    "Medium":[
      "ping pong",
      "snowball",
      "roof",
      "fly",
      "fang ",
      "bicycle",
      "bear ",
      "cape ",
      "puppet",
      "piano ",
      "lipstick ",
      "salute",
      "hula hoop ",
      "penguin ",
      "banana peel",
      "whisper ",
      "popsicle ",
      "Frankenstein",
      "earthquake ",
      "yo-yo ",
      "road",
      "rain ",
      "alarm clock ",
      "dog leash",
      "chop ",
      "pajamas ",
      "slam dunk",
      "fiddle ",
      "seashell ",
      "jog",
      "seesaw ",
      "nap ",
      "cheerleader",
      "blind ",
      "beg ",
      "shopping ",
      "cart",
      "Michael Jackson ",
      "limbo ",
      "newspaper",
      "twist ",
      "rhinoceros ",
      "cow",
      "tickle ",
      "fetch ",
      "violin",
      "cage ",
      "cello ",
      "braid",
      "skateboard ",
      "stairs ",
      "trumpet",
      "mop ",
      "shovel ",
      "money",
      "soap ",
      "saddle ",
      "wink",
      "tree ",
      "Spider Man ",
      "think"
    ],
    "Hard":[
      "peck",
      "windmill",
      "party",
      "dentist",
      "lawn",
      "mower",
      "softball",
      "wig",
      "stain",
      "cuff",
      "sunburn",
      "funny",
      "sheet",
      "hair",
      "dryer",
      "nightmare",
      "iPad",
      "shadow",
      "wax",
      "fog",
      "sip",
      "bathroom",
      "scale",
      "taxi",
      "pizza",
      "sand",
      "huddle",
      "cowboy",
      "ticket",
      "doghouse",
      "stiff",
      "knot",
      "president",
      "owl",
      "wrench",
      "story",
      "whisk",
      "quicksand",
      "spine",
      "chess",
      "artist",
      "vest",
      "gingerbread",
      "man",
      "spider",
      "web",
      "bob",
      "lung",
      "washing",
      "machine",
      "oar",
      "torch",
      "eraser",
      "mini",
      "blinds",
      "mouse",
      "trap",
      "swordfish",
      "jar",
      "cramp",
      "flamingo",
      "cast",
      "honk",
      "mirror",
      "business",
      "trip",
      "chalk",
      "gym",
      "volcano"
    ],
    "Very Hard":[
      "Will Smith",
      "defect",
      "standing ovation",
      "flag",
      "retaliate",
      "mascot",
      "shipwreck",
      "jet lag",
      "comfort zone",
      "alphabetize",
      "application",
      "college",
      "lifestyle",
      "level",
      "invitation",
      "applesauce",
      "crumb",
      "loyalty",
      "corduroy",
      "fizz",
      "shrink ray",
      "game plan",
      "personal bubble",
      "déjà vu",
      "Olympian ",
      "oil ",
      "procrastinate",
      "criticize ",
      "space-time continuum ",
      "ergonomic",
      "regret ",
      "teenager ",
      "organize",
      "baby monitor ",
      "Beethoven ",
      "streamline",
      "satellite ",
      "gratitude ",
      "journal",
      "a cappella ",
      "beanstalk ",
      "explore",
      "mine shaft ",
      "dismantle ",
      "weed killer",
      "tachometer ",
      "unemployed ",
      "portfolio",
      "pomp ",
      "evolution ",
      "apathy",
      "advertise ",
      "roundabout ",
      "sandbox",
      "conversation ",
      "negotiate ",
      "Zamboni",
      "silhouette ",
      "aisle ",
      "pendulum"
    ],
    "Actions":[
      "dancing a ballet ",
      "washing an elephant ",
      "rock climbing",
      "shopping at the mall ",
      "playing soccer ",
      "flying a kite",
      "going bowling ",
      "scuba diving ",
      "chasing a tornado",
      "building a campfire ",
      "sewing a dress ",
      "filming a movie ",
      "riding a carousel ",
      "playing chess",
      "finger painting ",
      "visiting the zoo ",
      "sewing on a button",
      "ironing a shirt ",
      "baking bread ",
      "making a pizza",
      "having a food fight ",
      "paddling in a canoe ",
      "delivering mail",
      "riding a motorcycle ",
      "flipping pancakes ",
      "sorting laundry",
      "playing hopscotch ",
      "hailing a taxi ",
      "landing an airplane",
      "watering a garden ",
      "mowing a lawn ",
      "raking leaves",
      "feeding the ducks ",
      "building a sandcastle ",
      "playing baseball",
      "milking a cow ",
      "setting up a tent ",
      "whale watching",
      "decorating for a party ",
      "trick-or-treating ",
      "walking with crutches",
      "riding in a chairlift ",
      "sumo wrestling ",
      "digging a hole",
      "riding bumper cars ",
      "practicing ",
      "karate hang-gliding",
      "cutting someone's hair",
      "swimming with dolphins",
      "playing with playdough",
      "going through airport security",
      "filling up a car with gas",
      "ordering food at a restaurant",
      "operating a jackhammer",
      "picking apples from a tree",
      "gathering eggs from a hen house",
      "watching a movie at the theater",
      "climbing Mount Everest",
      "going on an African safari",
      "performing at a rock concert",
      "playing at a piano recital",
      "asking for an autograph",
      "walking through a haunted house",
      "opening birthday presents",
      "body surfing at the beach",
      "painting the walls in a room",
      "being a flight attendant",
      "washing windows on a building"
    ]
  }
}